import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "./ui/main-page/footer";
import NavBar from "./ui/main-page/nabvar";
import { getDictionary } from "@/app/[lang]/dictionaries";
import { verifySession } from "@/app/lib/dal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: [
    {
      rel: "icon",
      url: "favicon-dark.svg",
      media: "(prefers-color-scheme: light)",
    },
    {
      rel: "icon",
      url: "favicon-light.svg",
      media: "(prefers-color-scheme: dark)",
    },
  ],
};

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "es" }];
}

export default async function RootLayout({
  params,
  children,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: "en" | "es" }>;
}>) {
  const dict = await getDictionary((await params).lang);
  const session = await verifySession();

  return (
    <html lang={(await params).lang} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar lang={dict.navbar} isLogged={session.isAuth} />
        {children}
        <Footer
          loveMessage={dict.footer.loveMessage}
          openSourceTitle={dict.footer.openSourceTitle}
        />
      </body>
    </html>
  );
}
